export type IngredientDefinition = {
  label: string;
  aliases?: string[];
};

// Nomi brevi per l'interfaccia e varianti realmente presenti nel dataset.
// Quantità, unità di misura, marche e indicazioni di preparazione sono escluse.
export const ingredientCatalog: IngredientDefinition[] = [
  { label: "Acqua" },
  { label: "Agretti" },
  { label: "Agar agar" },
  { label: "Aglio" },
  { label: "Agnello" },
  { label: "Albicocche" },
  { label: "Albume", aliases: ["albumi"] },
  { label: "Alloro" },
  { label: "Amido di mais", aliases: ["maizena"] },
  { label: "Ananas" },
  { label: "Aneto" },
  { label: "Anguria" },
  { label: "Arachidi", aliases: ["arachide"] },
  { label: "Arancia", aliases: ["arance", "buccia d'arancia"] },
  { label: "Asparagi" },
  { label: "Avocado" },
  { label: "Banana", aliases: ["banane"] },
  { label: "Barbabietola", aliases: ["barbabietole"] },
  { label: "Basilico" },
  { label: "Bicarbonato" },
  { label: "Bietole", aliases: ["bietola", "bietoline"] },
  { label: "Biscotti", aliases: ["biscotto", "savoiardi"] },
  { label: "Branzino", aliases: ["spigola"] },
  { label: "Broccoli", aliases: ["broccolo", "broccoletti"] },
  { label: "Brodo", aliases: ["brodo vegetale", "brodo di carne"] },
  { label: "Burro" },
  { label: "Cacao" },
  { label: "Cachi", aliases: ["caco"] },
  { label: "Caciocavallo" },
  { label: "Calamari", aliases: ["calamaro", "totano"] },
  { label: "Cannella" },
  { label: "Capperi" },
  { label: "Carciofi", aliases: ["carciofo"] },
  { label: "Carne macinata", aliases: ["macinato", "macinata"] },
  { label: "Carote", aliases: ["carota"] },
  { label: "Castagne", aliases: ["castagna"] },
  { label: "Cavolfiore" },
  { label: "Cavolo", aliases: ["cavoli"] },
  { label: "Cavolo romanesco", aliases: ["romanesco"] },
  { label: "Cavolini di Bruxelles", aliases: ["cavoli di Bruxelles"] },
  { label: "Ceci" },
  { label: "Cetriolo", aliases: ["cetrioli"] },
  { label: "Ciliegie", aliases: ["ciliegia"] },
  { label: "Cime di rapa", aliases: ["cime di broccoletti"] },
  { label: "Cioccolato", aliases: ["cioccolato fondente", "gocce di cioccolato"] },
  { label: "Cipolla", aliases: ["cipolle"] },
  { label: "Cipollotto", aliases: ["cipollotti", "cipollina"] },
  { label: "Cocco" },
  { label: "Coniglio" },
  { label: "Cous cous", aliases: ["couscous"] },
  { label: "Crusca" },
  { label: "Dentice" },
  { label: "Emmental", aliases: ["emmenthal"] },
  { label: "Erbe aromatiche", aliases: ["aromi", "erba aromatica"] },
  { label: "Fagioli", aliases: ["fagiolo", "cannellini", "borlotti"] },
  { label: "Fagiolini", aliases: ["fagiolino"] },
  { label: "Farina", aliases: ["farina 00", "farina manitoba"] },
  { label: "Farina di riso" },
  { label: "Farro" },
  { label: "Fave", aliases: ["fava"] },
  { label: "Fecola", aliases: ["fecola di patate"] },
  { label: "Fichi", aliases: ["fico"] },
  { label: "Finocchi", aliases: ["finocchio"] },
  { label: "Fontina" },
  { label: "Formaggio spalmabile", aliases: ["formaggio fresco spalmabile"] },
  { label: "Fragole", aliases: ["fragola"] },
  { label: "Frutta", aliases: ["frutta fresca", "frutta di stagione"] },
  { label: "Funghi", aliases: ["fungo", "champignon"] },
  { label: "Gallinella" },
  { label: "Gamberetti", aliases: ["gamberetto"] },
  { label: "Gelatina", aliases: ["colla di pesce"] },
  { label: "Ghiaccio" },
  { label: "Gorgonzola" },
  { label: "Grana", aliases: ["grana padano"] },
  { label: "Insalata", aliases: ["gentilina"] },
  { label: "Kiwi" },
  { label: "Lamponi", aliases: ["lampone"] },
  { label: "Latte", aliases: ["latte vaccino", "latte vegetale"] },
  { label: "Lattuga", aliases: ["lattuga romana"] },
  { label: "Lenticchie", aliases: ["lenticchia"] },
  { label: "Lievito", aliases: ["lievito per dolci", "lievito di birra", "lievito chimico"] },
  { label: "Limone", aliases: ["limoni", "succo di limone", "scorza di limone"] },
  { label: "Maiale", aliases: ["lonza", "lombata di maiale"] },
  { label: "Mais" },
  { label: "Maggiorana" },
  { label: "Malto", aliases: ["malto di mais"] },
  { label: "Mandorle", aliases: ["mandorla"] },
  { label: "Manzo" },
  { label: "Marmellata", aliases: ["confettura"] },
  { label: "Mascarpone" },
  { label: "Mela", aliases: ["mele", "golden", "renette", "ranette", "fuji"] },
  { label: "Melagrana" },
  { label: "Melanzane", aliases: ["melanzana"] },
  { label: "Melone" },
  { label: "Menta" },
  { label: "Merluzzo" },
  { label: "Miele" },
  { label: "Miglio" },
  { label: "Mollica", aliases: ["mollica di pane"] },
  { label: "Moscardini", aliases: ["moscardino"] },
  { label: "Mozzarella" },
  { label: "Nasello" },
  { label: "Noci" },
  { label: "Noce moscata" },
  { label: "Olio d’oliva", aliases: ["olio EVO", "olio extravergine", "olio extravergine di oliva", "olio d'oliva", "olio di oliva"] },
  { label: "Olio di semi", aliases: ["olio di semi di girasole"] },
  { label: "Olive", aliases: ["oliva"] },
  { label: "Origano" },
  { label: "Orata" },
  { label: "Orzo" },
  { label: "Palombo" },
  { label: "Pan carré", aliases: ["pancarré", "pancarrè"] },
  { label: "Pane", aliases: ["pane raffermo", "panini", "crostini"] },
  { label: "Pangrattato", aliases: ["pane grattugiato"] },
  { label: "Pandoro" },
  { label: "Panna" },
  { label: "Parmigiano", aliases: ["parmigiano reggiano"] },
  { label: "Pasta", aliases: ["pastina", "spaghetti", "spaghettini", "tagliatelle", "fusilli", "conchigliette", "orecchiette", "farfalle", "farfalline", "ditalini", "tubetti", "lumachine", "maccheroncini", "cavatelli", "corallini", "stelline", "anellini", "trofie", "lasagne"] },
  { label: "Pasta brisée", aliases: ["pasta brisè", "pasta brisee"] },
  { label: "Pasta frolla", aliases: ["frolla"] },
  { label: "Pasta sfoglia", aliases: ["sfoglia"] },
  { label: "Patate", aliases: ["patata"] },
  { label: "Pecorino" },
  { label: "Pepe" },
  { label: "Peperoni", aliases: ["peperone"] },
  { label: "Pere", aliases: ["pera"] },
  { label: "Pesca", aliases: ["pesche"] },
  { label: "Pesce spada", aliases: ["spada"] },
  { label: "Pinoli", aliases: ["pinolo"] },
  { label: "Piselli", aliases: ["pisello", "pisellini"] },
  { label: "Pistacchi", aliases: ["pistacchio"] },
  { label: "Platessa" },
  { label: "Pollo" },
  { label: "Pomodori", aliases: ["pomodoro", "pomodorini", "pomodorino", "ciliegino", "datterini", "pelati", "passata di pomodoro"] },
  { label: "Pompelmo" },
  { label: "Porro", aliases: ["porri"] },
  { label: "Prezzemolo" },
  { label: "Primosale" },
  { label: "Prosciutto cotto", aliases: ["prosciutto", "p.cotto"] },
  { label: "Provola" },
  { label: "Prugne", aliases: ["prugna"] },
  { label: "Quinoa" },
  { label: "Radicchio" },
  { label: "Rana pescatrice", aliases: ["pescatrice"] },
  { label: "Ricotta" },
  { label: "Ribes" },
  { label: "Riso", aliases: ["carnaroli", "arborio", "basmati", "vialone nano", "riso venere"] },
  { label: "Robiola" },
  { label: "Rosmarino" },
  { label: "Rucola" },
  { label: "Sale" },
  { label: "Salmone" },
  { label: "Salvia" },
  { label: "Scarola" },
  { label: "Scalogno" },
  { label: "Sedano" },
  { label: "Sedano rapa" },
  { label: "Semi di papavero", aliases: ["papavero"] },
  { label: "Semi di sesamo", aliases: ["sesamo"] },
  { label: "Semolino" },
  { label: "Seppioline", aliases: ["seppie", "seppiolina"] },
  { label: "Sgombro" },
  { label: "Sogliola", aliases: ["sogliole"] },
  { label: "Spinaci", aliases: ["spinacio", "spinacini"] },
  { label: "Stracchino" },
  { label: "Taleggio" },
  { label: "Tacchino" },
  { label: "Timo" },
  { label: "Tofu" },
  { label: "Tonno" },
  { label: "Topinambur" },
  { label: "Trota" },
  { label: "Tuorlo", aliases: ["tuorli", "tuorlo d'uovo"] },
  { label: "Uova", aliases: ["uovo"] },
  { label: "Uva", aliases: ["uvetta"] },
  { label: "Vaniglia", aliases: ["vanillina", "vanigliato"] },
  { label: "Verdure" },
  { label: "Verza" },
  { label: "Vitello" },
  { label: "Yogurt", aliases: ["yogurt greco"] },
  { label: "Zafferano" },
  { label: "Zenzero" },
  { label: "Zucca" },
  { label: "Zucchero", aliases: ["zucchero semolato", "zucchero di canna", "zucchero a velo"] },
  { label: "Zuccherini" },
  { label: "Zucchine", aliases: ["zucchina"] },
];
