"use client";
import { useEffect, useRef, useState } from "react";
import recipesData from "./recipes.json";

type Recipe = { title:string; category:string; ingredients:string[]; procedure_excerpt:string; dose:string; image_url:string; source_url:string };
const recipes = recipesData as Recipe[];
function normalizeWord(value:string){
 const normalized=value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
 if(normalized.length<4)return normalized;
 return normalized.replace(/(cchio|cchi)$/,"cch").replace(/(go|ghi)$/,"g").replace(/(ca|che)$/,"c").replace(/[aeiou]$/,"");
}
function normalizedWords(value:string){return value.split(/[^\p{L}\p{N}]+/u).map(normalizeWord).filter(Boolean)}
function containsNormalized(haystack:string,needle:string){
 const available=normalizedWords(haystack);
 return normalizedWords(needle).every(term=>available.some(word=>word===term||(term.length>=3&&word.startsWith(term))));
}
function hasIngredient(haystack:string,needle:string){
 const available=normalizedWords(haystack);
 return normalizedWords(needle).every(term=>available.includes(term));
}
function recipeType(recipe:Recipe){return recipe.category}
function nutritionBalance(recipe:Recipe){
 const protein=/pollo|tacchino|manzo|vitello|maiale|pesce|salmone|merluzzo|trota|tonno|uov|ricotta|yogurt|latte|formaggio|parmigiano|legum|lenticchi|ceci|fagiol|pisell|tofu/;
 const carbs=/pasta|riso|farina|pane|pangrattato|patat|polenta|miglio|avena|cous|semola|gnocch|zucchero|biscott|banana/;
 const vitamins=/carot|zucchin|spinaci|broccol|pomodor|zucca|finocch|lattuga|verdura|frutta|mela|pera|pesca|prugna|fragol|avocado|basilico|cavol|bietol|rapa|limone|arancia/;
 let scores=[1,1,1];recipe.ingredients.forEach(item=>{const value=item.toLowerCase();if(protein.test(value))scores[0]+=1.35;if(carbs.test(value))scores[1]+=1.2;if(vitamins.test(value))scores[2]+=1.25});
 const total=scores.reduce((a,b)=>a+b,0);const rounded=scores.map(value=>Math.round(value/total*100));rounded[2]+=100-rounded.reduce((a,b)=>a+b,0);return{protein:rounded[0],carbs:rounded[1],vitamins:rounded[2]};
}
const types=["Vegetariane","Carne","Pesce","Dolci e merende"];
const ingredientOptions=["Aglio","Arancia","Avocado","Banana","Basilico","Bietole","Broccoli","Brodo","Burro","Carne","Carote","Cavolfiore","Ceci","Cipolla","Farina","Fagioli","Fagiolini","Finocchi","Formaggio","Fragole","Latte","Lenticchie","Limone","Mais","Mela","Melanzane","Merluzzo","Nasello","Olio","Olive","Pane","Pangrattato","Panna","Parmigiano","Pasta","Patate","Pesce","Piselli","Pollo","Pomodori","Prezzemolo","Prosciutto","Ricotta","Riso","Robiola","Rosmarino","Salmone","Sedano","Spinaci","Tonno","Uova","Yogurt","Zucca","Zucchero","Zucchine"];
const balanceProfiles=["Tutti i bilanci","Bilanciata 50/25/25","Distribuzione uniforme","Più proteica","Più ricca di carboidrati","Più ricca di vitamine"];
function matchesBalance(recipe:Recipe,profile:string){
 const b=nutritionBalance(recipe);if(profile==="Tutti i bilanci")return true;
 if(profile==="Bilanciata 50/25/25")return Math.abs(b.carbs-50)<=10&&Math.abs(b.protein-25)<=8&&Math.abs(b.vitamins-25)<=8;
 if(profile==="Distribuzione uniforme")return Math.max(b.protein,b.carbs,b.vitamins)-Math.min(b.protein,b.carbs,b.vitamins)<=10;
 if(profile==="Più proteica")return b.protein>=b.carbs+5&&b.protein>=b.vitamins+5;
 if(profile==="Più ricca di carboidrati")return b.carbs>=b.protein+5&&b.carbs>=b.vitamins+5;
 return b.vitamins>=b.protein+5&&b.vitamins>=b.carbs+5;
}

export default function Home(){
 const[query,setQuery]=useState("");const[selectedIngredients,setSelectedIngredients]=useState<string[]>([]);const[draftIngredients,setDraftIngredients]=useState<string[]>([]);const[ingredientSearch,setIngredientSearch]=useState("");const[ingredientPickerOpen,setIngredientPickerOpen]=useState(false);const[type,setType]=useState("");const[maxIngredients,setMaxIngredients]=useState("Tutti");const[balanceProfile,setBalanceProfile]=useState("Tutti i bilanci");const[selected,setSelected]=useState<Recipe|null>(null);const[showBackTop,setShowBackTop]=useState(false);const[visibleCount,setVisibleCount]=useState(12);const[announcedCount,setAnnouncedCount]=useState(recipes.length);
 const ingredientTriggerRef=useRef<HTMLButtonElement>(null);const ingredientDialogRef=useRef<HTMLElement>(null);const ingredientCloseRef=useRef<HTMLButtonElement>(null);const randomTriggerRef=useRef<HTMLButtonElement>(null);const randomDialogRef=useRef<HTMLElement>(null);const randomCloseRef=useRef<HTMLButtonElement>(null);
 const filterRecipes=(ingredients:string[])=>recipes.filter(recipe=>{const text=`${recipe.title} ${recipe.category} ${recipe.procedure_excerpt}`;const ing=recipe.ingredients.join(" ");const q=!query.trim()||containsNormalized(text,query);const i=ingredients.every(item=>hasIngredient(ing,item));const t=!type||recipeType(recipe)===type;const c=maxIngredients==="Tutti"||recipe.ingredients.length<=Number(maxIngredients);return q&&i&&t&&c&&matchesBalance(recipe,balanceProfile)});
 const filtered=filterRecipes(selectedIngredients);
 const draftFiltered=filterRecipes(draftIngredients);
 const visibleIngredientOptions=ingredientOptions.filter(item=>!ingredientSearch.trim()||containsNormalized(item,ingredientSearch));
 const contextualIngredientCounts=Object.fromEntries(ingredientOptions.map(item=>[item,ingredientPickerOpen?filterRecipes(draftIngredients.includes(item)?draftIngredients:[...draftIngredients,item]).length:0]));
 const visibleRecipes=filtered.slice(0,visibleCount);
 const filtersActive=Boolean(query.trim()||selectedIngredients.length||type||maxIngredients!=="Tutti"||balanceProfile!=="Tutti i bilanci");
 const randomRecipe=()=>{const pool=filtered.length?filtered:recipes;setSelected(pool[Math.floor(Math.random()*pool.length)])};
 const clearFilters=()=>{setQuery("");setSelectedIngredients([]);setDraftIngredients([]);setType("");setMaxIngredients("Tutti");setBalanceProfile("Tutti i bilanci");setSelected(null)};
 const openIngredientPicker=()=>{setDraftIngredients(selectedIngredients);setIngredientSearch("");setIngredientPickerOpen(true)};
 const toggleDraftIngredient=(item:string)=>setDraftIngredients(current=>current.includes(item)?current.filter(value=>value!==item):[...current,item]);
 const applyIngredients=()=>{setSelectedIngredients(draftIngredients);setIngredientPickerOpen(false);window.setTimeout(()=>document.getElementById("recipe-results")?.scrollIntoView({behavior:"smooth",block:"start"}),0)};
 useEffect(()=>{setVisibleCount(12)},[query,selectedIngredients,type,maxIngredients,balanceProfile]);
 useEffect(()=>{const timer=window.setTimeout(()=>setAnnouncedCount(filtered.length),450);return()=>window.clearTimeout(timer)},[filtered.length]);
 useEffect(()=>{if(!selected)return;randomCloseRef.current?.focus();const handleKeys=(event:KeyboardEvent)=>{if(event.key==="Escape"){setSelected(null);return}if(event.key!=="Tab"||!randomDialogRef.current)return;const focusable=[...randomDialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",handleKeys);const previousOverflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",handleKeys);document.body.style.overflow=previousOverflow;randomTriggerRef.current?.focus()}},[selected]);
 useEffect(()=>{if(!ingredientPickerOpen)return;ingredientCloseRef.current?.focus();const handleKeys=(event:KeyboardEvent)=>{if(event.key==="Escape"){setIngredientPickerOpen(false);return}if(event.key!=="Tab"||!ingredientDialogRef.current)return;const focusable=[...ingredientDialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",handleKeys);const previousOverflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",handleKeys);document.body.style.overflow=previousOverflow;ingredientTriggerRef.current?.focus()}},[ingredientPickerOpen]);
 useEffect(()=>{const update=()=>setShowBackTop(window.scrollY>520);update();window.addEventListener("scroll",update,{passive:true});return()=>window.removeEventListener("scroll",update)},[]);
 return <main>
  <header className="hero"><nav className="nav-shell"><div className="brand"><img className="brand-logo" src="/brand-logo.svg" alt=""/><span>Buonissimo!</span></div><div className="nav-note">Le ricette provengono da Alimentazione Bambini, il sito sviluppato da Coop. Per informazioni sulla redazione scientifica, <a href="https://alimentazionebambini.e-coop.it/redazione/" target="_blank" rel="noreferrer">clicca qui</a>.</div></nav><section className="hero-content"><p className="eyebrow">Idee da portare in tavola · da 1 a 3 anni</p><h1>Oggi cosa<br/><em>prepariamo?</em></h1><p className="hero-credits">Sviluppato da Carlo, Elena e Marco</p><p className="hero-copy">Trova una ricetta partendo da quello che hai in frigo, oppure lascia decidere alla magia.</p><button className="magic-button" ref={randomTriggerRef} onClick={randomRecipe}><span>✦</span> Sorprendimi con una ricetta</button></section><div className="hero-orb hero-orb-one"/><div className="hero-orb hero-orb-two"/></header>
  <section className="filter-wrap" aria-label="Filtri ricette"><div className="filter-panel">
   <div className="primary-filters"><button className="ingredient-picker-button" ref={ingredientTriggerRef} onClick={openIngredientPicker}><span className="filter-icon" aria-hidden="true">＋</span><span><small>Parti da quello che hai</small><strong>{selectedIngredients.length?`${selectedIngredients.length} ingredienti selezionati`:"Scegli gli ingredienti"}</strong></span><b aria-hidden="true">→</b></button><label className="recipe-search"><span>Cerca per nome</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Polpette, risotto, crema…"/>{query?<button type="button" onClick={()=>setQuery("")} aria-label="Cancella ricerca">×</button>:<i aria-hidden="true">⌕</i>}</label></div>
   {selectedIngredients.length>0&&<div className="selected-ingredient-tags" aria-label="Ingredienti selezionati">{selectedIngredients.map(item=><button key={item} onClick={()=>setSelectedIngredients(current=>current.filter(value=>value!==item))}>{item}<span aria-hidden="true">×</span></button>)}</div>}
   <details className="advanced-filters"><summary><span>Filtri avanzati</span><small>{maxIngredients!=="Tutti"||balanceProfile!=="Tutti i bilanci"?"Filtri attivi":"Numero ingredienti e bilancio"}</small><b aria-hidden="true">⌄</b></summary><div className="advanced-filter-body"><label className="search-field"><span>Numero ingredienti</span><select value={maxIngredients} onChange={e=>setMaxIngredients(e.target.value)}><option>Tutti</option><option value="5">Massimo 5</option><option value="7">Massimo 7</option><option value="10">Massimo 10</option></select></label><label className="search-field balance-filter"><span>Bilancio</span><select value={balanceProfile} onChange={e=>setBalanceProfile(e.target.value)}>{balanceProfiles.map(item=><option key={item}>{item}</option>)}</select></label><button className="clear-button" onClick={clearFilters}>Azzera tutti</button></div></details>
   <div className="category-filter" aria-label="Categorie ricette">{types.map(item=><button key={item} className={type===item?"active":""} aria-pressed={type===item} onClick={()=>setType(current=>current===item?"":item)}>{item}</button>)}</div>
  </div>{filtersActive&&<div className="mobile-filter-status"><span><strong>{filtered.length}</strong> {filtered.length===1?"ricetta trovata":"ricette trovate"}</span><button onClick={()=>document.getElementById("recipe-results")?.scrollIntoView({behavior:"smooth",block:"start"})}>Vedi ricette</button></div>}<span className="sr-only" aria-live="polite">{announcedCount} {announcedCount===1?"ricetta trovata":"ricette trovate"}</span></section>
  {ingredientPickerOpen&&<div className="ingredient-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setIngredientPickerOpen(false)}}><section className="ingredient-modal" ref={ingredientDialogRef} role="dialog" aria-modal="true" aria-labelledby="ingredient-modal-title" aria-describedby="ingredient-modal-help"><header><div><p>Scegli rapidamente</p><h2 id="ingredient-modal-title">Cosa hai in cucina?</h2></div><button ref={ingredientCloseRef} onClick={()=>setIngredientPickerOpen(false)} aria-label="Chiudi selezione ingredienti">×</button></header><p className="sr-only" id="ingredient-modal-help">Seleziona tutti gli ingredienti che devono essere presenti nelle ricette.</p>{draftIngredients.length>0&&<div className="ingredient-modal-selected"><div><strong>Le tue selezioni</strong><button onClick={()=>setDraftIngredients([])}>Azzera</button></div><div>{draftIngredients.map(item=><button key={item} onClick={()=>toggleDraftIngredient(item)} aria-label={`Rimuovi ${item}`}>{item}<span aria-hidden="true">×</span></button>)}</div></div>}<label className="ingredient-modal-search"><span aria-hidden="true">⌕</span><input value={ingredientSearch} onChange={event=>setIngredientSearch(event.target.value)} placeholder="Cerca un ingrediente…" aria-label="Cerca nell’elenco degli ingredienti"/></label><div className="ingredient-modal-toolbar"><span>{draftIngredients.length?`${draftIngredients.length} selezionati`:"Seleziona uno o più ingredienti"}</span></div><div className="ingredient-options">{visibleIngredientOptions.map(item=>{const isSelected=draftIngredients.includes(item);const count=contextualIngredientCounts[item];const unavailable=!isSelected&&count===0;return <button key={item} className={`${isSelected?"selected":""}${unavailable?" unavailable":""}`} aria-pressed={isSelected} disabled={unavailable} onClick={()=>toggleDraftIngredient(item)}><span>{isSelected?"✓":"+"}</span>{item}<small>{count}</small></button>})}{visibleIngredientOptions.length===0&&<p className="no-ingredients">Nessun ingrediente trovato.</p>}</div><footer><div aria-live="polite"><strong>{draftFiltered.length}</strong><span>{draftFiltered.length===1?" ricetta disponibile":" ricette disponibili"}</span></div><button onClick={applyIngredients}>Mostra {draftFiltered.length} {draftFiltered.length===1?"ricetta":"ricette"}</button></footer></section></div>}
  {selected&&<div className="recipe-dialog-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="recipe-dialog" ref={randomDialogRef} role="dialog" aria-modal="true" aria-labelledby="random-recipe-title" aria-describedby="random-recipe-description"><button className="dialog-close" ref={randomCloseRef} onClick={()=>setSelected(null)} aria-label="Chiudi proposta">×</button><span className="dialog-spark" aria-hidden="true">✦</span><p className="dialog-eyebrow">La sorpresa di oggi</p><h2 id="random-recipe-title">{selected.title}</h2><p className="dialog-copy" id="random-recipe-description">Abbiamo scelto questa ricetta per te. Puoi aprirla senza perdere il punto in cui ti trovi nella pagina.</p><div className="dialog-actions"><a href={selected.source_url} target="_blank" rel="noreferrer">Apri la ricetta completa <span>↗</span></a><button onClick={randomRecipe}>Proponine un’altra</button></div></section></div>}
  <section className="content-shell" id="recipe-results"><div className="result-heading"><div><p className="eyebrow dark">La selezione</p><h2>{filtered.length} {filtered.length===1?"ricetta da provare":"ricette da provare"}</h2></div><p>{selectedIngredients.length?`Con ${selectedIngredients.join(", ")}`:"Filtra, scegli e porta in tavola qualcosa di buono."}</p></div>
   {filtered.length?<><div className="recipe-grid">{visibleRecipes.map(recipe=>{const slug=recipe.source_url.split("/").filter(Boolean).pop();const balance=nutritionBalance(recipe);return <article className="recipe-card" id={slug} key={recipe.source_url}><div className="image-wrap"><img src={recipe.image_url} alt={recipe.title} loading="lazy"/><span className={`type-badge type-${recipeType(recipe).toLowerCase().replaceAll(" ","-")}`}>{recipeType(recipe)}</span></div><div className="card-body"><div className="card-meta"><span>{recipe.ingredients.length} ingredienti</span>{recipe.dose&&<span>{recipe.dose}</span>}</div><h3>{recipe.title}</h3><details><summary>Vedi ingredienti</summary><ul>{recipe.ingredients.map((item,index)=><li key={index}>{item}</li>)}</ul>{recipe.procedure_excerpt&&<p className="procedure">{recipe.procedure_excerpt}</p>}</details><details className="nutrition-details" open><summary>Bilancio nutrizionale</summary><div className="nutrition-chart" aria-label={`Proteine ${balance.protein}%, carboidrati ${balance.carbs}%, vitamine ${balance.vitamins}%`}><span className="nutrition-protein" style={{width:`${balance.protein}%`}}/><span className="nutrition-carbs" style={{width:`${balance.carbs}%`}}/><span className="nutrition-vitamins" style={{width:`${balance.vitamins}%`}}/></div><div className="nutrition-legend"><span><i className="dot protein-dot"/>Proteine <b>{balance.protein}%</b></span><span><i className="dot carbs-dot"/>Carboidrati <b>{balance.carbs}%</b></span><span><i className="dot vitamins-dot"/>Vitamine <b>{balance.vitamins}%</b></span></div><p className="nutrition-note">Stima orientativa basata sugli ingredienti. “Vitamine” indica la quota di frutta e verdura, non una percentuale nutrizionale misurata.</p></details><a className="source-link" href={recipe.source_url} target="_blank" rel="noreferrer">Ricetta completa <span>↗</span></a></div></article>})}</div><div className="load-more-wrap"><p>Mostrate {visibleRecipes.length} di {filtered.length} ricette</p>{visibleRecipes.length<filtered.length&&<button onClick={()=>setVisibleCount(count=>count+12)}>Mostra altre ricette</button>}</div></>:<div className="empty-state"><span>🥕</span><h3>Nessuna ricetta trovata</h3><p>Prova a usare un ingrediente più semplice o ad azzerare i filtri.</p><button onClick={clearFilters}>Azzera i filtri</button></div>}
  </section><footer><span>Buonissimo!</span><p>Una raccolta di ricette per bambini da 1 a 3 anni. Verifica sempre allergeni e consistenze adatte al tuo bambino.</p></footer>{showBackTop&&<button className="back-to-top" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} aria-label="Torna in cima"><span aria-hidden="true">↑</span><b>Torna in cima</b></button>}
 </main>
}
